title: Web Accessibility Initiative (WAI)
email: your-email@domain.com
description: |
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: /wcag-act-rules
url: https://w3c.github.io
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - _external
  - Gemfile
  - Gemfile.lock
  - README.md
  - w3c.json
  - node_modules
repository: w3c/wcag-act-rules
branch: main
markdown: kramdown
kramdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
theme: wai-website-theme
collections:
  wai-wcag-act-rules-patterns:
    title: Glossary
    permalink: /:collection/:name/
    output: true
defaults:
  - scope:
      path: ''
    values:
      class: tight-page
      layout: act_rule
      external_css: /content-assets/wcag-act-rules/act-styles.css
      feedbackmail: group-act-rules@w3.org
      footer: >
        <p><strong>Date:</strong> Updated @@ Month 2021. First published Month
        20@@.</p> <p><strong>Editors:</strong> @@name, @@name.
        <strong>Contributors:</strong> @@name, @@name, and <a
        href="https://www.w3.org/groups/wg/@@wg/participants">participants of
        the @@WG</a>. ACKNOWLEDGEMENTS lists contributors and credits.</p>
        <p>Developed by the @@ Working Group (<a
        href="http://www.w3.org/WAI/@@/">@@WG</a>). Developed as part of the <a
        href="https://www.w3.org/WAI/@@/">WAI-@@ project</a>, @@co-funded by the
        European Commission.</p>
      type_of_guidance: ACT Rule
      rule_meta:
        rule_type: Atomic rule
      sidebar: true
      github:
        hide: true
      standalone_resource_header:
        title: ACT Rules
        title-ref: /standards-guidelines/act/rules/
        subtitle: Rules for Accessibility Conformance Testing (ACT)
      standalone_resource_nav_links:
        - name: All Rules
          ref: /standards-guidelines/act/rules/
        - name: About
          ref: /standards-guidelines/act/rules/about/
        - name: Implementations
          ref: /standards-guidelines/act/implementations/
        - name: Glossary
          ref: /standards-guidelines/act/rules/glossary/
